version: '3'
services:
  mysql:
    image: mysql_image
    build: /home/ubuntu/Docker_Project/db_docker
    container_name: mysql_container
    environment:
    - MYSQL_DATABASE=shiv
    - MYSQL_USER=shiv
    - MYSQL_PASSWORD=shiv12345
    - MYSQL_ROOT_PASSWORD=shiv123456
    volumes:
    - MysqlVolume:/var/lib/mysql
  backend:
    image: backend_image
    build: /home/ubuntu/Docker_Project/backend
    container_name: backendcontainer
    links:
    - mysql
    volumes:
    - /home/ubuntu/Docker_Project:/new_chatapp

  frontend:
    image: frontend_image
    build: /home/ubuntu/Docker_Project/frontend_Docker 
    container_name: frontendcontainer
    links:
    - backend
    ports:
    - 81:80
    
  proxy:
    image: proxy_image
    build: /home/ubuntu/Docker_Project/proxy
    container_name: proxy_container
    links:
    - frontendcontainer
    ports:
    - 80:80
volumes:
  MysqlVolume:
